### ISSUE TITLE
Scan mdx

### ISSUE THREAD

**Issue by actboy168** [ladislav-zezula/W3xNameScanner#1]
See the http://www.wc3c.net/tools/specs/NubMdxFormat.txt
The TEXS chunk is an array.

https://github.com/ladislav-zezula/W3xNameScanner/blob/master/DlgNameScanner.cpp#L950

```
for (size_t pos = 0; pos < pBlockHdr->dwBlockSize; pos += 268)
{
    CheckNameVariants(pData, (char *)(pBlockHdr + 1) + sizeof(DWORD) + pos);
}
```

**Comment by ladislav-zezula** [comment]
Fixed in commit 6cf82529cc32d6144645269405af0d46dd596c23.
Sorry for the long delay, I forgot to set this repo as "Watched".
