### ISSUE TITLE
IsTextFile

### ISSUE THREAD

**Issue by actboy168** [ladislav-zezula/W3xNameScanner#3]
It will return false, if the file is an chinese text file.

**Comment by ladislav-zezula** [comment]
Do you have an example of a chinese map? Please, send it to me to zezula_at_volny_dot_cz

**Comment by actboy168** [comment]
ok

**Comment by ladislav-zezula** [comment]
Got it, will look ať it ASAP.

**Comment by ladislav-zezula** [comment]
Yeah, it does not work well for English test files either. I changed the "IsTextFile" a bit. Now it works better, but I still think it could be improved. Got 51 unknowns in the DotA_(v_6.81d).w3x (with no initial listfile).

**Comment by actboy168** [comment]
In the w3x, the text file must be an utf8 file.So I think it uses IsUtf8File replace IsTextFile.Just like

https://github.com/actboy168/YDWE/blob/master/Development/Editor/Core/ydbase/base/util/is_utf8.cpp

**Comment by ladislav-zezula** [comment]
The question is, when there is an object with Chinese name, what will the name of the BLP/MDX be? I assume it will use the same string, just  with its extension?

**Comment by actboy168** [comment]
Your patch is ok. It is anoher question, for the 51 unknowns.It need more known file.

Units\CampaignAbilityFunc.txt
Units\CampaignAbilityStrings.txt
Units\CampaignUnitFunc.txt
Units\CampaignUnitStrings.txt
Units\CampaignUpgradeFunc.txt
Units\CampaignUpgradeStrings.txt
Units\CommonAbilityFunc.txt
Units\CommonAbilityStrings.txt
Units\HumanAbilityFunc.txt
Units\HumanAbilityStrings.txt
Units\HumanUnitFunc.txt
Units\HumanUnitStrings.txt
Units\HumanUpgradeFunc.txt
Units\HumanUpgradeStrings.txt
Units\ItemAbilityFunc.txt
Units\ItemAbilityStrings.txt
Units\ItemData.slk
Units\ItemFunc.txt
Units\ItemStrings.txt
Units\NeutralAbilityFunc.txt
Units\NeutralAbilityStrings.txt
Units\NeutralUnitFunc.txt
Units\NeutralUnitStrings.txt
Units\NeutralUpgradeFunc.txt
Units\NeutralUpgradeStrings.txt
Units\NightElfAbilityFunc.txt
Units\NightElfAbilityStrings.txt
Units\NightElfUnitFunc.txt
Units\NightElfUnitStrings.txt
Units\NightElfUpgradeFunc.txt
Units\NightElfUpgradeStrings.txt
Units\OrcAbilityFunc.txt
Units\OrcAbilityStrings.txt
Units\OrcUnitFunc.txt
Units\OrcUnitStrings.txt
Units\OrcUpgradeFunc.txt
Units\OrcUpgradeStrings.txt
Units\UndeadAbilityFunc.txt
Units\UndeadAbilityStrings.txt
Units\UndeadUnitFunc.txt
Units\UndeadUnitStrings.txt
Units\UndeadUpgradeFunc.txt
Units\UndeadUpgradeStrings.txt
Units\UnitAbilities.slk
Units\UnitBalance.slk
Units\UnitData.slk
Units\UnitUI.slk
Units\UnitWeapons.slk

and so on

**Comment by ladislav-zezula** [comment]
Correction: If you don;t enter any input file at all, there will be 72 unknowns. 51 it is with "Warcraft III Maps.txt" as input listfile. I'll investigate whether I can improve the name scanner to get also these few 21 files, maybe I figure out something that allows us to go even lower.

**Comment by ladislav-zezula** [comment]
Ok, first problem I found is the files in "Fonts" subdirectory. The game gets the font name from the JASS script:
call WE2("Fonts\\"+SubString(I2S(WG2),0,1)+".blp",90,90,x-20,y,0,true) 
where the font name can become (for example):
Fonts\\"+SubString(I2S(WG2),0,1)+".blp" --> "Fonts\\4.blp"
Can't figure out with static analysis, could be catchable by live scanner

**Comment by ladislav-zezula** [comment]
Commit f873795541dd2b20064bd4d15dbc82e94bcea045: Down to 5 unknowns in DotA_(v_6.81d).w3x without much cheating (aka names hard-coded in name scanner).

The remaining 4 BLP don't seem to have the name anywhere. The remaining MDX file has different name within itself. This is probably as far as I can get with this map. Keep them coming.
