### ISSUE TITLE
portrait.mdx

### ISSUE THREAD

**Issue by actboy168** [ladislav-zezula/W3xNameScanner#4]
If the map has a 'xxx.mdx', and the map may be has 'xxx_portrait.mdx'.

**Comment by ladislav-zezula** [comment]
Is this an example of a single map or a general rule?

**Comment by actboy168** [comment]
I have sent you a mail.

**Comment by ladislav-zezula** [comment]
Yeah I see that there is:
war3mapImported\saber.mdx
war3mapImported\saber_portrait.mdx

BUT

Is this a common scenario? I mean, if someone adds a MDX file to war3mapImported subdirectory (via map editor), does it add two MDX files (normal and "_portrait")?

The reason I am asking is that if this is done on custom behalf, adding it to name scanner will not help much - next time, people can add war3mapImported\xxx_portr2.mdx to fool the name scanner.

I am maybe asking stupid question, but my knowledge about map structure is next to zero - never created a single map, so I don't know all the tricks that can be used.

**Comment by actboy168** [comment]
Yes, portrait.mdx is special. You only set xxx.mdx for an unit in the map editor, and war3 will be try open xxx.mdx and xxxr_portrait.mdx .

![mdx](https://cloud.githubusercontent.com/assets/1836844/7880010/30b538d6-0628-11e5-8994-87028948faa5.jpg)

**Comment by ladislav-zezula** [comment]
I see. I'll add it to the scanner.
Why is there no single xxx_portrait.mdx in the DotA_(v_6.81d).w3x map?

**Comment by actboy168** [comment]
It is not necessary.

**Comment by ladislav-zezula** [comment]
Added in commit d0de3ff156c441518ff146738b7701b375963d0b.
In the "test.w3x", all names are detected (0 unknowns).
