### ISSUE TITLE
Search Splats\*.slk

### ISSUE THREAD

**Issue by actboy168** [ladislav-zezula/W3xNameScanner#5]
For the Splats\LightningData.slk  (If map has it)

Name| Dir | file
------- | ---- | ----
INIT | ReplaceableTextures\Weather | Lightning.blp
CLPB | ReplaceableTextures\Weather | Lightning.blp
CLSB | ReplaceableTextures\Weather | Lightning.blp
MBUR | ReplaceableTextures\Weather | ManaBurnBeam.blp

It means you can seach 

ReplaceableTextures\Weather\Lightning.blp
ReplaceableTextures\Weather\Lightning.blp
ReplaceableTextures\Weather\Lightning.blp
ReplaceableTextures\Weather\ManaBurnBeam.blp

**Comment by ladislav-zezula** [comment]
I covered this more generally. It seems that in SLK files, the "C;X3;K" always prepend a possible directory. The SLK scanner added in commit f873795541dd2b20064bd4d15dbc82e94bcea045 covers this.

**Comment by actboy168** [comment]
The slk scanner has some questions.

SLK is a table like xls.And you can open SLK file by MS-Execl.
This is a SLK parser for lua.
https://gist.github.com/actboy168/5c7e57497264a471f64d

**Comment by ladislav-zezula** [comment]
Yeah, SLK is basically a CSV file - each line is a table row, values are separated by semicolon (;). However, in Name Scanner, I only care about the values in quotation marks and try to get some names from them.

**Comment by actboy168** [comment]
If I can write the SLK like that
···
C;X3;Y1;K"ReplaceableTextures\Weather"
C;Y2;K"ReplaceableTextures\Weather"
C;Y3;K"ReplaceableTextures\Weather"
···
And the SLK scanner does not work. well .

**Comment by ladislav-zezula** [comment]
The algorithm takes everything that begins with "C;X3;Y1 as directory. When a directory is found, it scans it with the previous file name. When a non-directory is found, it also checks it with the previously found directory (if any).

Yes, by tampering the SLK file, you can prevent name scanning, as long as the game does not need the string for anything.
